export const UPLOAD_HOUSE_REQUEST = 'UPLOAD_HOUSE_REQUEST';
export const UPLOAD_HOUSE_SUCCESS = 'UPLOAD_HOUSE_SUCCESS';
export const UPLOAD_HOUSE_FAIL = 'UPLOAD_HOUSE_FAIL';
export const UPLOAD_HOUSE_RESET = 'UPLOAD_HOUSE_RESET';

export const GET_USER_UPLOADED_HOUSE_REQUEST =
  'GET_USER_UPLOADED_HOUSE_REQUEST';
export const GET_USER_UPLOADED_HOUSE_SUCCESS =
  'GET_USER_UPLOADED_HOUSE_SUCCESS';
export const GET_USER_UPLOADED_HOUSE_FAIL = 'GET_USER_UPLOADED_HOUSE_FAIL';
