export const UPLOAD_HOUSE_REQUEST = 'UPLOAD_HOUSE_REQUEST';
export const UPLOAD_HOUSE_SUCCESS = 'UPLOAD_HOUSE_SUCCESS';
export const UPLOAD_HOUSE_FAIL = 'UPLOAD_HOUSE_FAIL';
export const UPLOAD_HOUSE_RESET = 'UPLOAD_HOUSE_RESET';

export const GET_USER_UPLOADED_REQUEST = 'GET_USER_UPLOADED_REQUEST';
export const GET_USER_UPLOADED_SUCCESS = 'GET_USER_UPLOADED_SUCCESS';
export const GET_USER_UPLOADED_FAIL = 'GET_USER_UPLOADED_FAIL';
export const RESET_GET_USER_UPLOAD = 'RESET_GET_USER_UPLOAD';

export const DELETE_HOUSE_REQUEST = 'DELETE_HOUSE_REQUEST';
export const DELETE_HOUSE_SUCCESS = 'DELETE_HOUSE_SUCCESS';
export const DELETE_HOUSE_FAIL = 'DELETE_HOUSE_FAIL';
export const DELETE_HOUSE_RESET = 'DELETE_HOUSE_RESET';

export const UPDATE_HOUSE_REQUEST = 'UPDATE_HOUSE_REQUEST';
export const UPDATE_HOUSE_SUCCESS = 'UPDATE_HOUSE_SUCCESS';
export const UPDATE_HOUSE_FAIL = 'UPDATE_HOUSE_FAIL';
export const UPDATE_HOUSE_RESET = 'UPDATE_HOUSE_RESET';

export const UPDATE_HOUSE_IMAGE_REQUEST = 'UPDATE_HOUSE_IMAGE_REQUEST';
export const UPDATE_HOUSE_IMAGE_SUCCESS = 'UPDATE_HOUSE_IMAGE_SUCCESS';
export const UPDATE_HOUSE_IMAGE_FAIL = 'UPDATE_HOUSE_IMAGE_FAIL';
export const UPDATE_HOUSE_IMAGE_RESET = 'UPDATE_HOUSE_IMAGE_RESET';

export const DELETE_HOUSE_IMAGE_REQUEST = 'DELETE_HOUSE_IMAGE_REQUEST';
export const DELETE_HOUSE_IMAGE_SUCCESS = 'DELETE_HOUSE_IMAGE_SUCCESS';
export const DELETE_HOUSE_IMAGE_FAIL = 'DELETE_HOUSE_IMAGE_FAIL';
export const DELETE_HOUSE_IMAGE_RESET = 'DELETE_HOUSE_IMAGE_RESET';

export const FETCH_HOUSE_REQUEST = 'FETCH_HOUSE_REQUEST';
export const FETCH_HOUSE_SUCCESS = 'FETCH_HOUSE_SUCCESS';
export const FETCH_HOUSE_FAIL = 'FETCH_HOUSE_FAIL';
export const FETCH_HOUSE_RESET = 'FETCH_HOUSE_RESET';
