// LOCATION MANAGEMENT
export const CREATE_REGION_REQUEST = 'CREATE_REGION_REQUEST';
export const CREATE_REGION_SUCCESS = 'CREATE_REGION_SUCCESS';
export const CREATE_REGION_FAIL = 'CREATE_REGION_FAIL';
export const RESET_CREATE_STATE = 'RESET_CREATE_STATE';

export const GET_ALL_REGION_REQUEST = 'GET_ALL_REGION_REQUEST';
export const GET_ALL_REGION_SUCCESS = 'GET_ALL_REGION_SUCCESS';
export const GET_ALL_REGION_FAIL = 'GET_ALL_REGION_FAIL';
export const RESET_GET_ALL_REGION = 'RESET_GET_ALL_REGION';

export const ADD_STATE_REQUEST = 'ADD_STATE_REQUEST';
export const ADD_STATE_SUCCESS = 'ADD_STATE_SUCCESS';
export const ADD_STATE_FAIL = 'ADD_STATE_FAIL';
export const RESET_ADD_STATE = 'RESET_ADD_STATE';

export const ADD_LOCAL_GOV_REQUEST = 'ADD_LOCAL_GOV_REQUEST';
export const ADD_LOCAL_GOV_SUCCESS = 'ADD_LOCAL_GOV_SUCCESS';
export const ADD_LOCAL_GOV_FAIL = 'ADD_LOCAL_GOV_FAIL';
export const RESET_ADD_LOCAL_GOV = 'RESET_ADD_LOCAL_GOV';

export const ADD_TOWN_REQUEST = 'ADD_TOWN_REQUEST';
export const ADD_TOWN_SUCCESS = 'ADD_TOWN_SUCCESS';
export const ADD_TOWN_FAIL = 'ADD_TOWN_FAIL';
export const RESET_ADD_TOWN = 'RESET_ADD_TOWN';

export const DELETE_STATE_REQUEST = 'DELETE_STATE_REQUEST';
export const DELETE_STATE_SUCCESS = 'DELETE_STATE_SUCCESS';
export const DELETE_STATE_FAIL = 'DELETE_STATE_FAIL';
export const RESET_DELETE_STATE = 'RESET_DELETE_STATE';

export const DELETE_LOCAL_GOV_REQUEST = 'DELETE_LOCAL_GOV_REQUEST';
export const DELETE_LOCAL_GOV_SUCCESS = 'DELETE_LOCAL_GOV_SUCCESS';
export const DELETE_LOCAL_GOV_FAIL = 'DELETE_LOCAL_GOV_FAIL';
export const RESET_DELETE_LOCAL_GOV = 'RESET_DELETE_LOCAL_GOV';

export const DELETE_TOWN_REQUEST = 'DELETE_TOWN_REQUEST';
export const DELETE_TOWN_SUCCESS = 'DELETE_TOWN_SUCCESS';
export const DELETE_TOWN_FAIL = 'DELETE_TOWN_FAIL';
export const RESET_DELETE_TOWN = 'RESET_DELETE_TOWN';

export const DELETE_COUNTRY_REQUEST = 'DELETE_COUNTRY_REQUEST';
export const DELETE_COUNTRY_SUCCESS = 'DELETE_COUNTRY_SUCCESS';
export const DELETE_COUNTRY_FAIL = 'DELETE_COUNTRY_FAIL';
export const RESET_DELETE_COUNTRY = 'RESET_DELETE_COUNTRY';

export const EDIT_STATE_REQUEST = 'EDIT_STATE_REQUEST';
export const EDIT_STATE_SUCCESS = 'EDIT_STATE_SUCCESS';
export const EDIT_STATE_FAIL = 'EDIT_STATE_FAIL';
export const RESET_EDIT_STATE = 'RESET_EDIT_STATE';

export const EDIT_LGA_REQUEST = 'EDIT_LGA_REQUEST';
export const EDIT_LGA_SUCCESS = 'EDIT_LGA_SUCCESS';
export const EDIT_LGA_FAIL = 'EDIT_LGA_FAIL';
export const RESET_EDIT_LGA = 'RESET_EDIT_LGA';

export const EDIT_TOWN_REQUEST = 'EDIT_TOWN_REQUEST';
export const EDIT_TOWN_SUCCESS = 'EDIT_TOWN_SUCCESS';
export const EDIT_TOWN_FAIL = 'EDIT_TOWN_FAIL';
export const RESET_EDIT_TOWN = 'RESET_EDIT_TOWN';
