export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';

export const CHANGE_PROFILE_PICTURE_REQUEST = 'CHANGE_PROFILE_PICTURE_REQUEST';
export const CHANGE_PROFILE_PICTURE_SUCCESS = 'CHANGE_PROFILE_PICTURE_SUCCESS';
export const CHANGE_PROFILE_PICTURE_FAIL = 'CHANGE_PROFILE_PICTURE_FAIL';
export const CHANGE_PROFILE_PICTURE_RESET = 'CHANGE_PROFILE_PICTURE_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const RESET_USER_DETAILS = 'RESET_USER_DETAILS';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const RESET_DELETE_USER = 'RESET_DELETE_USER';

export const ACTIVATE_USER_REQUEST = 'ACTIVATE_USER_REQUEST';
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS';
export const ACTIVATE_USER_FAIL = 'ACTIVATE_USER_FAIL';
export const RESET_ACTIVATE_USER = 'RESET_ACTIVATE_USER';

export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAIL = 'BLOCK_USER_FAIL';
export const RESET_BLOCK_USER = 'RESET_BLOCK_USER';

export const DE_ACTIVATE_USER_REQUEST = 'DE_ACTIVATE_USER_REQUEST';
export const DE_ACTIVATE_USER_SUCCESS = 'DE_ACTIVATE_USER_SUCCESS';
export const DE_ACTIVATE_USER_FAIL = 'DE_ACTIVATE_USER_FAIL';
export const RESET_DE_ACTIVATE_USER = 'RESET_DE_ACTIVATE_USER';

export const PROMOTE_USER_REQUEST = 'PROMOTE_USER_REQUEST';
export const PROMOTE_USER_SUCCESS = 'PROMOTE_USER_SUCCESS';
export const PROMOTE_USER_FAIL = 'PROMOTE_USER_FAIL';
export const RESET_PROMOTE_USER = 'RESET_PROMOTE_USER';

export const DEMOTE_USER_REQUEST = 'DEMOTE_USER_REQUEST';
export const DEMOTE_USER_SUCCESS = 'DEMOTE_USER_SUCCESS';
export const DEMOTE_USER_FAIL = 'DEMOTE_USER_FAIL';
export const RESET_DEMOTE_USER = 'DEMOTE_USER_FAIL';
