// import { UserDashboardDataInterface, UserDashboardInterface } from './types';

import { User_Dashboard_img_1 } from '../../assets/images';
import {
  UserDashboardDataInterface,
  UserDashboardInterface,
} from '../../types/user-dashboard/user_dashboard_nav';

export const userDashboardNavValues: Array<UserDashboardInterface> = [
  {
    link: '/dashboard/user',
    name: 'dashboard',
    text: 'dashboard',
  },
  {
    link: '/dashboard/user/application',
    name: 'application',
    text: 'application',
  },
  {
    link: '/dashboard/user/favourite',
    name: 'favourite',
    text: 'favourite',
  },
];

export const userDashboardDataValues: Array<UserDashboardDataInterface> = [
  {
    address: '1995 Broadway, New York',
    image: User_Dashboard_img_1,
    // likeIcon: Like,
    // locationIcon: '',
    interior: [
      'Wifi',
      'Air conditioning',
      'Kitchen',
      'Heating',
      'Smokers',
      'Parking',
      'Balcony',
      'Animal friendly',
    ],
    rating: 4.5,
    reviews: 7,
    title: ' Lovely room in Manhattan',
    rentPermonth: 3000,
  },
  {
    address: '1995 Broadway, New York',
    image: User_Dashboard_img_1,
    // likeIcon: Like,
    // locationIcon: '',
    interior: [
      'Wifi',
      'Air conditioning',
      'Kitchen',
      'Heating',
      'Smokers',
      'Parking',
      'Balcony',
      'Animal friendly',
    ],
    rating: 4.5,
    reviews: 7,
    title: ' Brownstone Lodge',
    rentPermonth: 4000,
  },
  {
    address: '1995 Broadway, New York',
    image: User_Dashboard_img_1,
    // likeIcon: Like,
    // locationIcon: '',
    interior: [
      'Wifi',
      'Air conditioning',
      'Kitchen',
      'Heating',
      'Smokers',
      'Parking',
      'Balcony',
      'Animal friendly',
    ],
    rating: 4.5,
    reviews: 7,
    title: ' Room in a boutique building',
    rentPermonth: 3500,
  },
  {
    address: '1995 Broadway, New York',
    image: User_Dashboard_img_1,
    // likeIcon: Like,
    // locationIcon: '',
    interior: [
      'Wifi',
      'Air conditioning',
      'Kitchen',
      'Heating',
      'Smokers',
      'Parking',
      'Balcony',
      'Animal friendly',
    ],
    rating: 4.5,
    reviews: 7,
    title: ' Brownstone Lodge',
    rentPermonth: 3800,
  },
  {
    address: '1995 Broadway, New York',
    image: User_Dashboard_img_1,
    // likeIcon: Like,
    // locationIcon: '',
    interior: [
      'Wifi',
      'Air conditioning',
      'Kitchen',
      'Heating',
      'Smokers',
      'Parking',
      'Balcony',
      'Animal friendly',
    ],
    rating: 4.5,
    reviews: 7,
    title: ' Brownstone Lodge',
    rentPermonth: 4200,
  },
  {
    address: '1995 Broadway, New York',
    image: User_Dashboard_img_1,
    // likeIcon: Like,
    // locationIcon: '',
    interior: [
      'Wifi',
      'Air conditioning',
      'Kitchen',
      'Heating',
      'Smokers',
      'Parking',
      'Balcony',
      'Animal friendly',
    ],
    rating: 4.5,
    reviews: 7,
    title: ' ABrownstone Lodge',
    rentPermonth: 3900,
  },
];
